title: Using Automation To Support Quality Assured Jupyter Notebook Publishing Processes
author: Tony Hirst
copyright: "2021" 
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 60  
parse:
  myst_dmath_double_inline: true

